/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author enviniom
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
        this.setExtendedState(frmInicio.MAXIMIZED_BOTH);
        this.setTitle("Sistema de reserva de parqueadero");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        lblApellidom = new javax.swing.JLabel();
        lblIDPersona = new javax.swing.JLabel();
        lblAcceso = new javax.swing.JLabel();
        lblApellidop = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnInicio = new javax.swing.JMenu();
        mnArchivo = new javax.swing.JMenu();
        mnTrabajadores = new javax.swing.JMenuItem();
        mnVehiculos = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(92, 144, 217));

        lblApellidom.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblApellidom.setText("jLabel1");
        escritorio.add(lblApellidom);
        lblApellidom.setBounds(10, 110, 190, 20);

        lblIDPersona.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblIDPersona.setText("jLabel1");
        escritorio.add(lblIDPersona);
        lblIDPersona.setBounds(10, 20, 190, 20);

        lblAcceso.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblAcceso.setText("jLabel1");
        escritorio.add(lblAcceso);
        lblAcceso.setBounds(10, 140, 190, 20);

        lblApellidop.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblApellidop.setText("jLabel1");
        escritorio.add(lblApellidop);
        lblApellidop.setBounds(10, 80, 190, 20);

        lblNombre.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblNombre.setText("jLabel1");
        escritorio.add(lblNombre);
        lblNombre.setBounds(10, 50, 190, 20);

        mnInicio.setMnemonic('f');
        mnInicio.setText("Reserva");
        mnInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnInicioKeyPressed(evt);
            }
        });
        menuBar.add(mnInicio);

        mnArchivo.setMnemonic('e');
        mnArchivo.setText("Archivo");

        mnTrabajadores.setMnemonic('y');
        mnTrabajadores.setText("Trabajadores");
        mnTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTrabajadoresActionPerformed(evt);
            }
        });
        mnArchivo.add(mnTrabajadores);

        mnVehiculos.setMnemonic('d');
        mnVehiculos.setText("Vehículos");
        mnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVehiculosActionPerformed(evt);
            }
        });
        mnArchivo.add(mnVehiculos);

        menuBar.add(mnArchivo);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Consultas");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Pagos");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Sin salir");
        helpMenu.add(aboutMenuItem);

        jMenuItem1.setText("Accesos");
        helpMenu.add(jMenuItem1);

        menuBar.add(helpMenu);

        jMenu1.setText("Salir");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnInicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnInicioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnInicioKeyPressed

    private void mnTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTrabajadoresActionPerformed
        // TODO add your handling code here:
        frmTrabajador form = new frmTrabajador();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnTrabajadoresActionPerformed

    private void mnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVehiculosActionPerformed
        // TODO add your handling code here:
        frmVehiculos form = new frmVehiculos();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnVehiculosActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JLabel lblAcceso;
    public static javax.swing.JLabel lblApellidom;
    public static javax.swing.JLabel lblApellidop;
    public static javax.swing.JLabel lblIDPersona;
    public static javax.swing.JLabel lblNombre;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu mnArchivo;
    private javax.swing.JMenu mnInicio;
    private javax.swing.JMenuItem mnTrabajadores;
    private javax.swing.JMenuItem mnVehiculos;
    // End of variables declaration//GEN-END:variables

}
